version: '3'

services:
    pccontroller-webapi:
        # replace by your built image
        image: pc_controller_backend:1.3-armv6
        # must be privileged to use GPIO and Serial (easiest way)
        privileged: true
        # link to domain with Traefik
        networks:
          - traefik
        labels:
          #- "traefik.port=80"
          #- "traefik.http.routers.pccontroller-webapi.rule=Host(`api.snoiry.com`) && Path(`/PCcontroller`)"
          - "traefik.enable=true"
          - "traefik.http.routers.pccontroller-webapi.rule=Host(`api.snoiry.com`) && Path(`/PCcontroller`)"
          #- "traefik.http.routers.pccontroller-webapi.entrypoints=websecure"
          #- "traefik.http.routers.pccontroller-webapi.tls.certresolver=snoiryresolver"
        restart: always

networks:
  traefik:
    external: true
